### ISSUE TITLE
What do some parameters in a makefile mean?Any examples?

### ISSUE THREAD

**Issue by mdzz9527** [4n4nd/train-prometheus#4]
What do some parameters in a makefile mean?Any examples?

**Comment by mdzz9527** [comment]
bearer_token=

block_storage_access_key=
block_storage_secret_key=
block_storage_bucket_name=
block_storage_endpoint_url=

What do these parameters mean?

**Comment by durandom** [comment]
@Mr-Pluto  these are for accessing a prometheus instance behind an oauth proxy.
I suggest you move to the new version at https://github.com/AICoE/prometheus-anomaly-detector
